apps/blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^blog/$', views.BlogView.as_view(), name='blog'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^contact/$', views.ContactView.as_view(), name='contact'),
    url(r'^article/(?P<article_id>\d+)$', views.ArticleDetailView.as_view(), name='detail'),
    url(r'^category/(?P<category_id>\d+)$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<tag_id>\d+)$', views.TagView.as_view(), name='tag'),
    url(r'^archive/(?P<year>[0-9]{4})/$', views.ArticleYearArchiveView.as_view(), name='archive_year'),
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]+)/$',
        views.ArticleMonthArchiveView.as_view(),
        name="archive_month_numeric"),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'', include('comments.urls')),
    url(r'', include('django_comments.urls')),
    url(r'', include('accounts.urls')),
    url(r'', include('registration.backends.default.urls')),
    url(r'', include('django.contrib.auth.urls')),
    url(r'^search/', include('haystack.urls')),
    url('^notifications/', include('notifications.urls', namespace='notifications')),
    url(r'^likes/', include('likes.urls', namespace='pinax_likes')),
    url(r'', include('social_login.urls', namespace='social_login')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

apps/templates/search/search.html
{% extends 'base.html' %}
{% load highlight %}
{% block content %}
    {#  TO-DO: page.object_list is a paginated results  #}
    <div class="content-body">
        <div class="container">
            <div class="row">
                <main class="col-md-8">
                    {% if query %}
                        {% for result in page.object_list %}
                            <article class="post post-{{ result.object.pk }}">
                                <header class="entry-header">
                                    <h1 class="entry-title">
                                        <a href="{% url 'blog:detail' result.object.pk %}">{{ result.object.title }}</a>
                                    </h1>
                                    <div class="entry-meta">
                                    <span class="post-category"><a
                                            href="{% url 'blog:category' result.object.category.pk %}">{{ result.object.category.name }}</a></span>

                                    <span class="post-date">
                                        <a href="#">
                                            <time class="entry-date"
                                                  datetime="{{ result.object.created_time }}">{{ result.object.created_time|date:'Y年n月j日' }}</time>
                                        </a>
                                    </span>

                                        <span class="post-author"><a
                                                href="#">{{ result.object.author.username }}</a></span>
                                        {% load comments_tags %}
                                        {% get_comment_count for result.object as num_comments %}

                                        <span class="comments-link"><a href="#">{{ num_comments }} 评论</a></span>
                                        <span class="post-views"><a href="#">{{ result.object.views }} 阅读</a></span>
                                    </div>
                                </header>
                                <div class="entry-content clearfix">
                                    {% load markdown_deux_tags %}
                                    <p>{% highlight result.object.body with query %}</p>
                                </div>
                            </article>
                        {% empty %}
                            <p>没有搜到任何结果！</p>
                        {% endfor %}
                    {% endif %}
                </main>
                {% block aside %}
                    {% include 'blog/sidebar.html' %}
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}