apps/blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^blog/$', views.BlogView.as_view(), name='blog'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^contact/$', views.ContactView.as_view(), name='contact'),
    url(r'^article/(?P<article_id>\d+)$', views.ArticleDetailView.as_view(), name='detail'),
    url(r'^category/(?P<category_id>\d+)$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<tag_id>\d+)$', views.TagView.as_view(), name='tag'),
    url(r'^archive/(?P<year>[0-9]{4})/$', views.ArticleYearArchiveView.as_view(), name='archive_year'),
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]+)/$',
        views.ArticleMonthArchiveView.as_view(),
        name="archive_month_numeric"),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'', include('comments.urls')),
    url(r'', include('django_comments.urls')),
    url(r'', include('accounts.urls')),
    url(r'', include('registration.backends.default.urls')),
    url(r'', include('django.contrib.auth.urls')),
    url(r'^search/', include('haystack.urls')),
    url('^notifications/', include('notifications.urls', namespace='notifications')),
    url(r'^likes/', include('likes.urls', namespace='pinax_likes')),
    url(r'', include('social_login.urls', namespace='social_login')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

apps/blog/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
from ckeditor_uploader.fields import RichTextUploadingField
class Article(models.Model):
    STATUS_CHOICES = (
        ('d', '草稿'),
        ('p', '发表'),
    )

    title = models.CharField('标题', max_length=200)
    #body = models.TextField('正文')
    body = RichTextUploadingField('正文')
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_mod_time = models.DateTimeField('修改时间', auto_now=True)
    pub_time = models.DateTimeField('发布时间', blank=True, null=True,
                                    help_text="不指定发布时间则视为草稿，可以指定未来时间，到时将自动发布。")
    status = models.CharField('文章状态', max_length=1, choices=STATUS_CHOICES)
    summary = models.CharField('摘要', max_length=200, blank=True, help_text="可选，若为空将摘取正文的前54个字符。")
    views = models.PositiveIntegerField('浏览量', default=0)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='作者', on_delete=models.CASCADE)

    category = models.ForeignKey('Category', verbose_name='分类', on_delete=models.CASCADE)
    tags = models.ManyToManyField('Tag', verbose_name='标签集合', blank=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-pub_time']
        verbose_name = "文章"
        verbose_name_plural = verbose_name

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'article_id': self.pk})

    def save(self, *args, **kwargs):
        self.summary = self.summary or self.body[:120]
        super().save(*args, **kwargs)

    def viewed(self):
        self.views += 1
        self.save(update_fields=['views'])


class Category(models.Model):
    name = models.CharField('分类名', max_length=30)
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_mod_time = models.DateTimeField('修改时间', auto_now=True)

    class Meta:
        ordering = ['name']
        verbose_name = "分类"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField('标签名', max_length=30)
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_mod_time = models.DateTimeField('修改时间', auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = "标签"
        verbose_name_plural = verbose_name

apps/blog/views.py
from django.db.models.aggregates import Count
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, FormView
from django.views.generic.dates import YearArchiveView, MonthArchiveView
from django.views.generic import TemplateView
from django.utils.safestring import mark_safe
import os,sys
import markdown2

from .models import Article, Category, Tag


class IndexView(ListView):
    template_name = "blog/index.html"
    def get_queryset(self):

        return Article.objects.filter(status='p')


class BlogView(ListView):
    template_name = "blog/blog.html"

    def get_queryset(self):
        return Article.objects.filter(status='p')


class AboutView(TemplateView):
    template_name = 'blog/about.html'


class ContactView(TemplateView):
    template_name = 'blog/contact.html'


class ArticleDetailView(DetailView):
    model = Article
    template_name = "blog/detail.html"
    pk_url_kwarg = 'article_id'

    def get_object(self, queryset=None):
        obj = super(ArticleDetailView, self).get_object(queryset=None)
        obj.body = mark_safe(markdown2.markdown(obj.body, extras=['fenced-code-blocks', 'code-friendly', 'codehilite']))
        # BUG:必须在这里渲染，如果在模板中通过模板标签渲染则格式会乱掉
        obj.viewed()
        return obj


class CategoryView(ListView):
    template_name = "blog/index.html"

    def get_queryset(self):
        return Article.objects.filter(category=self.kwargs['category_id'], status='p')


class TagView(ListView):
    template_name = "blog/index.html"

    def get_queryset(self):
        return Article.objects.filter(tags=self.kwargs['tag_id'], status='p')


class ArticleYearArchiveView(YearArchiveView):
    queryset = Article.objects.all()
    date_field = "created_time"
    make_object_list = True
    context_object_name = 'article_list'
    template_name = 'blog/index.html'


class ArticleMonthArchiveView(MonthArchiveView):
    queryset = Article.objects.all()
    date_field = "created_time"
    context_object_name = 'article_list'
    template_name = 'blog/index.html'
    month_format = '%m'

apps/templates/blog/about.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="content-body">
        <div class="container">
            <div class="row">
                <main class="col-md-12">
                    <h1 class="page-title">ABOUT ME</h1>
                    <article class="post">
                        <div class="entry-content clearfix">
                            <figure class="img-responsive-center">
                                <img class="img-responsive" src="{% static 'blog/img/me.png' %}" alt="Developer Image">
                            </figure>
                            <p style="text-align: center">THE GROWTH PATH OF A ROOKIE</p>

                            <div class="height-40px"></div>
{#                            <h2 class="title text-center">社交账号</h2>#}
{#                            <ul class="social">#}
{#                                <li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>#}
{#                                <li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>#}
{#                                <li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>#}
{#                                <li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>#}
{#                            </ul>#}
                        </div>
                    </article>
                </main>
            </div>
        </div>
    </div>
{% endblock %}

apps/templates/blog/blog.html
{% extends 'base.html' %}
{% block content %}
    <div class="content-body">
        <div class="container">
            <div class="row">
                <main class="col-md-12">
                    {% for article in article_list %}
                        <article class="post post-{{ article.pk }}">
                            <header class="entry-header">
                                <h1 class="entry-title">
                                    <a href="{% url 'blog:detail' article.pk %}">{{ article.title }}</a>
                                </h1>
                                <div class="entry-meta">
                                    <span class="post-category"><a
                                            href="{% url 'blog:category' article.category.pk %}">{{ article.category.name }}</a></span>

                                    <span class="post-date">
                                        <a href="#">
                                            <time class="entry-date"
                                                  datetime="{{ article.created_time }}">{{ article.created_time|date:'Y年n月j日' }}</time>
                                        </a>
                                    </span>

                                    <span class="post-author"><a href="#">{{ article.author.username }}</a></span>
                                    {% load comments_tags %}
                                    {% get_comment_count for article as num_comments %}

                                    <span class="comments-link"><a href="#">{{ num_comments }} 评论</a></span>
                                    <span class="post-views"><a href="#">{{ article.views }} 阅读</a></span>
                                </div>
                            </header>
                            <div class="entry-content clearfix">
                                {% load markdown_deux_tags %}
                                <p>{{ article.abstract |markdown | truncatechars_html:'54' }}</p>
                                <div class="read-more cl-effect-14">
                                    <a href="{% url 'blog:detail' article.pk %}" class="more-link">继续阅读 <span
                                            class="meta-nav">→</span></a>
                                </div>
                            </div>
                        </article>
                    {% endfor %}
                </main>
            </div>
        </div>
    </div>
{% endblock %}

apps/templates/blog/contact.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="content-body">
        <div class="container">
            <div class="row">
                <main class="col-md-12">
                    <h1 class="page-title">联系我</h1>
                    <article class="post">
                        <div class="entry-content clearfix">
                            <form action="#" method="post" class="contact-form">
                                <div class="row">
                                    <div class="col-md-6 col-md-offset-3">
                                        <input type="text" name="name" placeholder="Name" required>
                                        <input type="email" name="email" placeholder="Email" required>
                                        <input type="text" name="subject" placeholder="Subject" required>
                                        <textarea name="message" rows="7" placeholder="Your Message"
                                                  required></textarea>
                                        <button class="btn-send btn-5 btn-5b ion-ios-paperplane">
                                            <span>给我发信</span></button>
                                    </div>
                                </div>    <!-- row -->
                            </form>
                        </div>
                    </article>
                </main>
            </div>
        </div>
    </div>
{% endblock %}

apps/templates/blog/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load markdown_deux_tags %}
{% load comments %}
{% load comments_tags %}
{% block content %}
    <div class="content-body">
        <div class="container">
            <div class="row">
                <main class="col-md-8">
                    <article class="post post-1 typo">
                        <header class="entry-header">
                            <h1 class="entry-title">{{ article.title }}</h1>
                            <div class="entry-meta">
                                <span class="post-category"><a
                                        href="{% url 'blog:category' article.category.pk %}">{{ article.category.name }}</a></span>

                                <span class="post-date">
                                    <a href="#">
                                        <time class="entry-date"
                                              datetime="{{ article.created_time }}">{{ article.created_time|date:'Y年n月j日' }}
                                        </time>
                                    </a>
                                </span>

                                <span class="post-author"><a href="#">{{ article.author.username }}</a></span>
                                {% get_comment_count for article as num_comments %}
                                <span class="comments-link"><a href="#">{{ num_comments }} 评论</a></span>
                                <span class="post-views"><a href="#">{{ article.views }} 阅读</a></span>
                            </div>
                        </header>
                        <div class="entry-content clearfix">
                            {{ article.body }}
                        </div>
                    </article>
                    {% if user.is_anonymous %}
                        <div class="login-reminder">您尚未登录，请在 <a href="{% url 'login' %}">登录</a> 后评论：</div>
                    {% endif %}
                    {% render_comment_form for article %}


                    {% render_comment_list for article %}
                </main>
                {% block aside %}
                    {% include 'blog/sidebar.html' %}
                {% endblock %}
            </div>
        </div>
    </div>



{% endblock %}

apps/templates/blog/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="content-body">
        <div class="container">
            <div class="row">
                <main class="col-md-8">
                    {% for article in article_list %}
                        <article class="post post-{{ article.pk }}">
                            <header class="entry-header">
                                <h1 class="entry-title">
                                    <a href="{% url 'blog:detail' article.pk %}">{{ article.title }}</a>
                                </h1>
                                <div class="entry-meta">
                                    <span class="post-category"><a
                                            href="{% url 'blog:category' article.category.pk %}">{{ article.category.name }}</a></span>

                                    <span class="post-date">
                                        <a href="#">
                                            <time class="entry-date"
                                                  datetime="{{ article.created_time }}">{{ article.created_time|date:'Y年n月j日' }}</time>
                                        </a>
                                    </span>

                                    <span class="post-author"><a href="#">{{ article.author.username }}</a></span>
                                    {% load comments_tags %}
                                    {% get_comment_count for article as num_comments %}

                                    <span class="comments-link"><a href="#">{{ num_comments }} 评论</a></span>
                                    <span class="post-views"><a href="#">{{ article.views }} 阅读</a></span>
                                </div>
                            </header>
                            <div class="entry-content clearfix">
                                {% load markdown_deux_tags %}
                                <p>{{ article.abstract |markdown | truncatechars_html:'54' }}</p>
                                <div class="read-more cl-effect-14">
                                    <a href="{% url 'blog:detail' article.pk %}" class="more-link">继续阅读 <span
                                            class="meta-nav">→</span></a>
                                </div>
                            </div>
                        </article>
                    {% endfor %}
                </main>
                {% block aside %}
                    {% include 'blog/sidebar.html' %}
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

apps/templates/blog/sidebar.html
<aside class="col-md-4">
    <div class="widget widget-recent-posts">
        <h3 class="widget-title">最新文章</h3>
        <ul>{% for article in recent_articles %}
            <li>
                <a href="{% url 'blog:detail' article.pk %}">{{ article.title }}</a>
            </li>
        {% endfor %}
        </ul>
    </div>

    <div class="widget widget-category">
        <h3 class="widget-title">分类</h3>
        <ul>
            {% for category in category_list %}
                <li>
                    <a href="{% url 'blog:category' category.pk %}">{{ category.name }}</a><span style="float: right">(&nbsp;&nbsp;{{ category.num_articles }}&nbsp;&nbsp;)</span>
                </li>
            {% endfor %}
        </ul>
    </div>

    <div class="widget widget-archives">
        <h3 class="widget-title">归档</h3>
        {% regroup dates by year as dates_by_year %}
        <ul>
            {% for mouth in dates_by_year %}
                <li>
                    <a href="{% url 'blog:archive_year' mouth.grouper %}"> {{ mouth.grouper }} 年</a><i
                        class="{% if forloop.counter0 == 0 %}icon ion-minus{% else %}icon ion-plus{% endif %}"></i>
                    <ul>
                        {% for d in mouth.list %}
                            <li>
                                <a href="{% url 'blog:archive_month_numeric' mouth.grouper d|date:'m' %}">{{ d |date:'n' }}
                                    月
                                </a></li>
                        {% endfor %}
                    </ul>
                </li>
            {% endfor %}

        </ul>
    </div>

    <div class="widget widget-tag">
        <h3 class="widget-title">标签云</h3>
        {% for tag in tag_list %}
            <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}&nbsp;&nbsp;(&nbsp;&nbsp;{{ tag.num_articles }}&nbsp;&nbsp;)</a>
        {% endfor %}
    </div>


</aside>